### PR TITLE
fix: 🐛  Actually fix flipping of board when loading

### LINKED ISSUE #80: Fix bug where board reverts if the user flips the board while the game is still loading
While loading board state, will need to respect the facing side

### PR DESCRIPTION
**Pull request by a-human-bean**
Includes necessary changes that were missed in #81 .

Closes #80

### CODE REVIEW

File: xq_app/src/components/board/store.ts [hunk 1]
```diff
@@ -39,11 +39,12 @@ export function createBoardState(dimensions: Dimensions) {
 
   return {
     store,
-    updateBoardState: (boardStates: Layout[]) =>
+    loadBoardState: (boardStates: Layout[]) =>
       update((state) => {
         state.layouts = boardStates.map((layout) =>
           layout.map(newPoint(dimensions, state.facing !== RED)),
         );
+        state.activeLayout = state.layouts[0];
```
Comment (a-human-bean) [inline xq_app/src/components/board/store.ts:47]: Renamed to `loadBoardState` to show that `currentIndex` of `state.activeLayout` can only be 0. Controls are disabled at this point, until moves are made. Will become trickier once we allows users to branch out alternate lines (but should still be disabled during loading state, e.g. piece DnD does not update board state).

Comment (a-human-bean) [reply xq_app/src/components/board/store.ts:47]: #83 Referencing so I don't forget this notion
